dist: trusty
sudo: false

cache:
  directories:
    - lib

language: java
jdk:
  - oraclejdk8
  - openjdk8

# WRong syntax
#  mariadb: 5.5
#  mariadb: 10.0
#  mariadb: 10.1
#  mariadb: 10.2
#  postgresql: 9.4
#  postgresql: 9.5
addons:
  postgresql: 9.6

env:
  - DB=postgres
  - DB=mariadb

#      postgresql: 9.7
# https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version

# - https://github.com/oltpbenchmark/oltpbench/issues/137
#matrix:
#  allow_failures:
#    - jdk: oraclejdk9
#  include:
#    - addons:
#      mariadb: 5.5
#    - addons:
#      mariadb: 10.0
#    - addons:
#      mariadb: 10.1
#    - addons:
#      mariadb: 10.2
#    - addons:
#      postgresql: 9.4
#    - addons:
#      postgresql: 9.5
#    - addons:
#      postgresql: 9.6
#    - addons:
#      postgresql: 9.7

# While mariadb addon isn't used
#services:
#  - mysql


install:
  - if [ $DB == mariadb ]; then mysql -e "SELECT VERSION()";
    elif [ $DB == postgres ]; then psql -c "SELECT VERSION()" -U travis;
    fi
  - netstat -lant || ss -tn
  - for db in tpcc tpch tatp wikipedia resourcestresser twitter epinions ycsb
                                jpab seats auctionmark chbenchmark 
                                voter linkbench sibench noop
                                smallbank hyadapt ; do 
      [ $DB == mariadb ] && mysql -e "CREATE DATABASE IF NOT EXISTS $db" ;
      [ $DB == postgres ] && psql -c "create database $db" -U postgres ;
    done
  - if [ $DB == mariadb ]; then mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY 'travis'; GRANT ALL ON *.* TO 'travis'@'localhost'";
    elif [ $DB == postgres ] then psql -c "ALTER USER CURRENT_USER WITH PASSWORD 'travis'" -U travis;
    fi

# MySQL create user is probably one of the trust-container bugs for MySQL
# Will probably need the following to set a password
#  - mysql -e "SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('travis')";

# We pass a password here as <password></password> sends no password in the protocol
# rather than the blank one and therefore fails on MySQL.

script:
  - ant junit
  - if [ $DB == mariadb ]; then
      URLBASE=jdbc:mysql://localhost:3306/ ;
      DRIVER=com.mysql.jdbc.Driver ;
      TYPE=mysql ;
    elif [ $DB == postgres ]; then
      URLBASE=jdbc:postgresql://localhost:5432/ ;
      DRIVER=jdbc:org.postgresql.Driver ;
      TYPE=postgres ;
    fi
  - for test in sample_epinions_config.xml
                sample_tatp_config.xml
                sample_linkbench_config.xml
                sample_tpcc_config.xml
                sample_auctionmark_config.xml
                sample_voter_config.xml;
    do
      config="config/${test}";
      sed -i 
           -e "/<dbtype>/c\<dbtype>${TYPE}</dbtype>"
           -e "/<driver>/c\<driver>${DRIVER}</driver>"
           -e "/<DBUrl>/s|jdbc:[^:]*://[^/]*|${URLBASE}|"
           -e '/<username>/c\<username>travis</username>'
           -e '/<password>/c\<password>travis</password>'
           -e '/<scalefactor>/c\<scalefactor>1</scalefactor>'
           -e '/<terminals>/c\<terminals>3</terminals>'
           "${config}";
      testname=${test#sample_}; testname=${testname%_config.xml} ;
      ./oltpbenchmark --bench "${testname}" --config "${config}"  --create true    --load true   --execute true ;
    done
