dist: trusty
sudo: false

cache:
  directories:
    - lib

language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

services:
  - mysql
  - postgres

install: echo "Done"
before_script: ls -la  /usr/lib/jvm/
script: ant junit
