dist: trusty
sudo: false

cache:
  directories:
    - lib

language: java
jdk:
  - oraclejdk8
  - openjdk8

# https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version

#      - https://github.com/oltpbenchmark/oltpbench/issues/137
#matrix:
#  allow_failures:
#    - jdk: oraclejdk9

addons:
  mariadb: "10.2"
  postgresql: "9.7"

#matrix:
#  include:
#    - addons:
#      mariadb: 5.5
#    - addons:
#      mariadb: 10.0
#    - addons:
#      mariadb: 10.1
#    - addons:
#      mariadb: 10.2
#    - addons:
#      postgresql: 9.4
#    - addons:
#      postgresql: 9.5
#    - addons:
#      postgresql: 9.6
#    - addons:
#      postgresql: 9.7

#services:
#  - mysql
#  - postgres

install: echo "Done"
before_script:
  - psql -c 'create database oltpbench' -U postgres
  - mysql -e 'CREATE DATABASE IF NOT EXISTS oltpbench' 
  - mysql -e "CREATE USER 'user'@'localhost' IDENTIFIED BY 'password'; GRANT ALL ON *.* TO 'user'@'localhost' WITH GRANT OPTION" 

script:
  - ant junit
  - for db in tpcc tpch tatp wikipedia resourcestresser twitter epinions ycsb \
                                jpab seats auctionmark chbenchmark \
                                voter linkbench sibench noop \
                                smallbank hyadapt ; do \
      psql -c "create database $db" -U postgres ; \
      mysql -e "CREATE DATABASE IF NOT EXISTS $db" ; \
    done
  - sed -i -e '/<DBUrl>/s/server/localhost/' \
           -e '/<scalefactorconfig>/s/[0-9]*/1/' /sample_epinions_config.xml
  -  ./oltpbenchmark --bench epinions --config config/sample_epinions_config.xml  --create true    --load true   --execute true
