dist: trusty
sudo: false

cache:
  directories:
    - lib

language: java
jdk:
  - oraclejdk8
  - openjdk8
 #  - oraclejdk9 - https://github.com/oltpbenchmark/oltpbench/issues/137

services:
  - mysql
  - postgres

install: echo "Done"
before_script: ls -la  /usr/lib/jvm/
script: ant junit
